### ISSUE TITLE
Telemetry support

### ISSUE THREAD

**Issue by danybd** [markqvist/LibAPRS#17]
Hello,
First, thank you very much for the library! I want to send the voltage using aprs and I think the proper way is to use the telemetry messages defined in aprs. Are they being supported right now? If not I would try to implement it. Is there any impediment known?

**Comment by Noah517** [comment]
For a recent project, I needed to send telemetry as well. I found the easiest way to do this was to convert your value to a string and add it to the comment. If you need help with that I would suggest using the dtostrf() command to convert the value to a string. If you want to include more then one value in the comment or add some extra text you need to make the main comment and substitute the new comment values. Here is a simple example sketch

`
float voltageFloat = voltageValue();

char comment[] = "APRS Test, Voltage: 00";
char voltageString[] = "00";

dtostrf(voltageFloat, 1, 0, voltageString);

comment[20] = voltageString[0];
comment[21] = voltageString[1];

APRS_sendLoc(comment, strlen(comment));
.`

**Comment by danybd** [comment]
Thank you for the responses. I'll try the suggestions

**Comment by 4x4eb** [comment]
hi,
can you share the final telemetry code please?
I have same need and I am looking for some telemetry support.

Eitan
