### ISSUE TITLE
Does anyone use LibAPRS I am having problems at PTT

### ISSUE THREAD

**Issue by uguraltinsoy** [markqvist/LibAPRS#33]
I am using the LibAPRS library and my problem is that the default PTT time is too short and the signal is not fully transmitted. How can I bypass it and make my own continuous TX, the signal is much cleaner.

https://www.youtube.com/watch?v=PrCiLKZh58M

**Comment by markqvist** [comment]
Closing since this is not an issue, but a support request. Question was answered on the discussion forum though.

**Comment by Henriquegravina** [comment]
APRS_setPreamble( value in ms );
