### ISSUE TITLE
rpt_list is not terminated

### ISSUE THREAD

**Issue by db1sb** [markqvist/LibAPRS#5]
AX25.cpp must be changed 👍
 for (msg.rpt_count = 0; !(*buf++ & 0x01) && (msg.rpt_count < countof(msg.rpt_list)); msg.rpt_count++) {
        DECODE_CALL(buf, msg.rpt_list[msg.rpt_count].call);
        msg.rpt_list[msg.rpt_count].call[6] = 0; //db1sb: terminate rpt_list-entries
        msg.rpt_list[msg.rpt_count].ssid = (*buf >> 1) & 0x0F;
        AX25_SET_REPEATED(&msg, msg.rpt_count, (*buf & 0x80));
    }

**Comment by markqvist** [comment]
Closed as fixed by your pull request. Thanks!
